package request;

import com.example.diploma.User;

public enum ClientsAction {
    SIGNUP,
    SIGNIN,
    CREATEPROJECT,
    GETUSERS,
    GETPROJECTSBYAUTHOR,
    GETPROJECTSBYUSER,
    CREATETASK,
    GETUSERSBYPROJECT,
    ADDPROJECTUSERS,
    GETTASKSBYUSER,
    UPDATESTATUS,
    SENDMESSAGE,
    GETINFCLIENT,
    GETTASKSBYPROJECT,
    UPDATETASKNAME,
    UPDATETASKDURATION,
    UPDATETASKSTATUS,
    UPDATETASKPERCENT,
    UPDATETASKPARENTID,
    UPDATETASKUSER,
    DELETETASK,
    GETTASKSBYPROJECTBYUSER,
    UPDATETASKDELAY,
}
