package request;

public enum ClientsAction {
    SIGNUP,
    SIGNIN,
    CREATEPROJECT,
    GETUSERS,
    GETPROJECTSBYAUTHOR,
    GETPROJECTSBYUSER,
    CREATETASK,
    GETUSERSBYPROJECT,
    ADDPROJECTUSERS,
    GETTASKSBYUSER,
    UPDATESTATUS
}
